name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Dobby233Liu/download-mingw@main
      id: mingw
    - name: fix path
      run: |
        set GITHUB_PATH="${{ steps.mingw.outputs.path }}\bin;%GITHUB_PATH%"
        refreshenv
    - name: build resources
      run: windres resource.rc -O coff -o resource.res
    - name: build exec
      run: ${{ steps.mingw.outputs.path }}\bin\gcc -m32 -static -lgdi32 -lgdiplus -mwindows -O3 -o winemine.exe dialog.c main.c resource.res
    - uses: actions/upload-artifact@v2
      with:
        path: winemine.exe
