on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        install: >-
          mingw-w64-i686-gcc
          mingw-w64-i686-binutils
          make
    - name: build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        path: winemine.exe
