on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        install: >-
          mingw-w64-i686-toolchain
    - name: build resources
      run: windres resource.rc -O coff -F pe-i386 -o resource.res
    - name: build exec
      run: gcc -m32 -static -nodefaultlibs -nostdlib -s -m32 -mwindows -O2 -w -march=i486 -o winemine.exe dialog.c main.c resource.res -lgdi32 -lgdiplus -luser32 -lkernel32 -lgdi32 -lcomctl32 -ladvapi32 -lshell32 -Wl,-e_start
    - uses: actions/upload-artifact@v2
      with:
        path: winemine.exe
